spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.url=jdbc:postgresql://dpg-d7li9tgg4nts73d07b10-a.oregon-postgres.render.com:5432/order_db_0807

spring.datasource.username=order_db_0807_user
spring.datasource.password=7uwvDzxwGal6EW3chhGwwkkGYyOlIOPM

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Allow frontend on 3000 to access backend
spring.web.resources.add-mappings=true
server.port=${PORT:8080}

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=quickbite.service0@gmail.com
spring.mail.password=oesfzmnwkizfwthe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
 
 # HikariCP connection pool for better performance
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.max-lifetime=1800000

google.client-id=685090660066-3b32naq25nt1032cc4pj2s0edrtu1vfc.apps.googleusercontent.com
